/**
 * Seed data para reportes de residuos
 * Reportes variados para historial y estadísticas
 */

// IDs de ciudadanos
const citizenIds = [
    '674c1a1b2c3d4e5f6a7b8ca2', // Ana López
    '674c1a1b2c3d4e5f6a7b8ca3', // Roberto Flores
    '674c1a1b2c3d4e5f6a7b8ca4', // Laura Martínez
    '674c1a1b2c3d4e5f6a7b8ca5', // Diego Herrera
    '674c1a1b2c3d4e5f6a7b8ca6', // Patricia Vega
    '674c1a1b2c3d4e5f6a7b8ca7', // Fernando Castro
    '674c1a1b2c3d4e5f6a7b8ca8', // Mónica Ruiz
    '674c1a1b2c3d4e5f6a7b8ca9', // Javier Morales
    '674c1a1b2c3d4e5f6a7b8caa', // Silvia Paredes
    '674c1a1b2c3d4e5f6a7b8cab', // Andrés Jiménez
];

export const wasteReportsData = [
    // === Ana López (15 reportes) ===
    {
        userId: citizenIds[0],
        type: 'OVERFLOW',
        description: 'Contenedor desbordado en la esquina del parque Vicente León, basura esparcida en la acera',
        coordinates: { type: 'Point', coordinates: [-78.6156, -0.9346] },
        address: 'Parque Vicente León, Latacunga Centro',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-01-15T08:30:00Z'),
        resolvedAt: new Date('2026-01-15T14:00:00Z'),
    },
    {
        userId: citizenIds[0],
        type: 'ILLEGAL_DUMP',
        description: 'Basura acumulada en terreno baldío cerca del mercado, incluye desechos orgánicos y plásticos',
        coordinates: { type: 'Point', coordinates: [-78.6178, -0.9325] },
        address: 'Calle Belisario Quevedo y Sánchez de Orellana',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 30,
        createdAt: new Date('2026-01-22T10:15:00Z'),
        resolvedAt: new Date('2026-01-23T09:00:00Z'),
    },
    {
        userId: citizenIds[0],
        type: 'OVERFLOW',
        description: 'Contenedor lleno en la zona residencial, ya no cabe más basura',
        coordinates: { type: 'Point', coordinates: [-78.6200, -0.9360] },
        address: 'Av. Amazonas y Guayaquil',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-01-28T07:45:00Z'),
        resolvedAt: new Date('2026-01-28T12:30:00Z'),
    },
    {
        userId: citizenIds[0],
        type: 'DAMAGED_CONTAINER',
        description: 'Contenedor con tapa rota y base agrietada, necesita reemplazo urgente',
        coordinates: { type: 'Point', coordinates: [-78.6130, -0.9380] },
        address: 'Calle Quito y Padre Salcedo',
        status: 'IN_PROGRESS',
        verifiedByAI: true,
        pointsAwarded: 20,
        createdAt: new Date('2026-02-05T09:00:00Z'),
    },
    {
        userId: citizenIds[0],
        type: 'MISSED_COLLECTION',
        description: 'El camión recolector no pasó por esta zona desde hace 3 días',
        coordinates: { type: 'Point', coordinates: [-78.6160, -0.9310] },
        address: 'Barrio San Agustín, calle Hermanas Páez',
        status: 'PENDING',
        verifiedByAI: false,
        pointsAwarded: 0,
        createdAt: new Date('2026-02-15T08:00:00Z'),
    },

    // === Roberto Flores (11 reportes) ===
    {
        userId: citizenIds[1],
        type: 'OVERFLOW',
        description: 'Contenedor rebosante junto a la escuela, riesgo sanitario para los estudiantes',
        coordinates: { type: 'Point', coordinates: [-78.6190, -0.9370] },
        address: 'Sector La Merced, Calle Juan Abel Echeverría',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-01-10T11:00:00Z'),
        resolvedAt: new Date('2026-01-10T16:20:00Z'),
    },
    {
        userId: citizenIds[1],
        type: 'ILLEGAL_DUMP',
        description: 'Acumulación de escombros y basura en quebrada cercana a la urbanización',
        coordinates: { type: 'Point', coordinates: [-78.6100, -0.9400] },
        address: 'Sector El Salto, cerca del río Cutuchi',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 30,
        createdAt: new Date('2026-01-18T14:30:00Z'),
        resolvedAt: new Date('2026-01-20T10:00:00Z'),
    },
    {
        userId: citizenIds[1],
        type: 'OVERFLOW',
        description: 'Punto de acopio saturado, basura en la calle afectando tránsito peatonal',
        coordinates: { type: 'Point', coordinates: [-78.6145, -0.9355] },
        address: 'Av. Eloy Alfaro y Quijano y Ordóñez',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-02-01T08:20:00Z'),
        resolvedAt: new Date('2026-02-01T15:00:00Z'),
    },
    {
        userId: citizenIds[1],
        type: 'DANGEROUS',
        description: 'Encontrados residuos hospitalarios en contenedor domiciliario, jeringuillas y gasas usadas',
        coordinates: { type: 'Point', coordinates: [-78.6170, -0.9340] },
        address: 'Calle Tarqui y General Maldonado',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 40,
        createdAt: new Date('2026-02-10T09:15:00Z'),
        resolvedAt: new Date('2026-02-10T11:00:00Z'),
    },

    // === Laura Martínez (7 reportes) ===
    {
        userId: citizenIds[2],
        type: 'OVERFLOW',
        description: 'Contenedor desbordado en esquina del parque, restos de comida atraen animales',
        coordinates: { type: 'Point', coordinates: [-78.6140, -0.9330] },
        address: 'Parque Náutico, sector San Felipe',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-01-20T15:40:00Z'),
        resolvedAt: new Date('2026-01-21T08:00:00Z'),
    },
    {
        userId: citizenIds[2],
        type: 'MISSED_COLLECTION',
        description: 'No se realizó la recolección programada del lunes por la mañana',
        coordinates: { type: 'Point', coordinates: [-78.6120, -0.9290] },
        address: 'Ciudadela del Chofer, calle principal',
        status: 'RESOLVED',
        verifiedByAI: false,
        pointsAwarded: 15,
        createdAt: new Date('2026-02-03T07:00:00Z'),
        resolvedAt: new Date('2026-02-03T12:30:00Z'),
    },
    {
        userId: citizenIds[2],
        type: 'ILLEGAL_DUMP',
        description: 'Botadero improvizado en terreno vacío, acumulación de bolsas y cajas',
        coordinates: { type: 'Point', coordinates: [-78.6205, -0.9315] },
        address: 'Sector La Laguna, Av. Oriente',
        status: 'PENDING',
        verifiedByAI: false,
        pointsAwarded: 0,
        createdAt: new Date('2026-02-12T11:20:00Z'),
    },

    // === Patricia Vega (12 reportes) ===
    {
        userId: citizenIds[4],
        type: 'OVERFLOW',
        description: 'Múltiples contenedores llenos en la zona del mercado, situación crítica',
        coordinates: { type: 'Point', coordinates: [-78.6165, -0.9350] },
        address: 'Mercado El Salto, Latacunga',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-01-12T06:30:00Z'),
        resolvedAt: new Date('2026-01-12T10:00:00Z'),
    },
    {
        userId: citizenIds[4],
        type: 'DAMAGED_CONTAINER',
        description: 'Contenedor volcado por el viento, basura esparcida en toda la cuadra',
        coordinates: { type: 'Point', coordinates: [-78.6195, -0.9380] },
        address: 'Barrio Nintinacazo, calle Los Álamos',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 20,
        createdAt: new Date('2026-01-25T13:00:00Z'),
        resolvedAt: new Date('2026-01-26T09:30:00Z'),
    },
    {
        userId: citizenIds[4],
        type: 'OVERFLOW',
        description: 'Punto de acopio completamente lleno, necesita recolección urgente',
        coordinates: { type: 'Point', coordinates: [-78.6150, -0.9365] },
        address: 'Sector San Sebastián, calle 2 de Mayo',
        status: 'PENDING',
        verifiedByAI: true,
        pointsAwarded: 0,
        createdAt: new Date('2026-02-16T08:00:00Z'),
    },

    // === Javier Morales (20 reportes - más activo) ===
    {
        userId: citizenIds[7],
        type: 'OVERFLOW',
        description: 'Contenedor principal del parque completamente saturado desde hace 2 días',
        coordinates: { type: 'Point', coordinates: [-78.6155, -0.9342] },
        address: 'Parque Vicente León, esquina sur',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-01-05T09:00:00Z'),
        resolvedAt: new Date('2026-01-05T14:00:00Z'),
    },
    {
        userId: citizenIds[7],
        type: 'ILLEGAL_DUMP',
        description: 'Gran acumulación de basura y muebles viejos en la ribera del río',
        coordinates: { type: 'Point', coordinates: [-78.6110, -0.9395] },
        address: 'Ribera del Río Cutuchi, sector sur',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 30,
        createdAt: new Date('2026-01-14T10:30:00Z'),
        resolvedAt: new Date('2026-01-16T08:00:00Z'),
    },
    {
        userId: citizenIds[7],
        type: 'DAMAGED_CONTAINER',
        description: 'Contenedor con ruedas rotas y sin tapa, imposible cerrarlo correctamente',
        coordinates: { type: 'Point', coordinates: [-78.6175, -0.9320] },
        address: 'Calle Antonia Vela y Félix Valencia',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 20,
        createdAt: new Date('2026-01-20T11:00:00Z'),
        resolvedAt: new Date('2026-01-22T09:00:00Z'),
    },
    {
        userId: citizenIds[7],
        type: 'DANGEROUS',
        description: 'Baterías de auto y aceite usado vertidos junto al contenedor público',
        coordinates: { type: 'Point', coordinates: [-78.6185, -0.9360] },
        address: 'Av. Cotopaxi, sector industrial',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 40,
        createdAt: new Date('2026-01-30T08:45:00Z'),
        resolvedAt: new Date('2026-01-30T12:00:00Z'),
    },
    {
        userId: citizenIds[7],
        type: 'OVERFLOW',
        description: 'Contenedor desbordado después de feriado, basura en toda la vereda',
        coordinates: { type: 'Point', coordinates: [-78.6140, -0.9350] },
        address: 'Calle Quito y Guayaquil, Centro',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-02-04T07:30:00Z'),
        resolvedAt: new Date('2026-02-04T11:00:00Z'),
    },
    {
        userId: citizenIds[7],
        type: 'MISSED_COLLECTION',
        description: 'La recolección no se realizó en el horario habitual, segunda vez esta semana',
        coordinates: { type: 'Point', coordinates: [-78.6160, -0.9335] },
        address: 'Sector La Estación, calle Márquez de Maenza',
        status: 'IN_PROGRESS',
        verifiedByAI: false,
        pointsAwarded: 15,
        createdAt: new Date('2026-02-14T07:00:00Z'),
    },
    {
        userId: citizenIds[7],
        type: 'OVERFLOW',
        description: 'Punto de reciclaje lleno, plásticos y cartones desbordando',
        coordinates: { type: 'Point', coordinates: [-78.6130, -0.9345] },
        address: 'Av. Unidad Nacional, frente al hospital',
        status: 'PENDING',
        verifiedByAI: true,
        pointsAwarded: 0,
        createdAt: new Date('2026-02-16T07:30:00Z'),
    },

    // === Diego Herrera (3 reportes) ===
    {
        userId: citizenIds[3],
        type: 'OVERFLOW',
        description: 'Contenedor de la esquina está lleno y huele muy mal',
        coordinates: { type: 'Point', coordinates: [-78.6188, -0.9340] },
        address: 'Sector El Carmen, calle Páez',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-02-08T09:30:00Z'),
        resolvedAt: new Date('2026-02-08T14:00:00Z'),
    },
    {
        userId: citizenIds[3],
        type: 'ILLEGAL_DUMP',
        description: 'Alguien dejó basura en la calle durante la noche, bolsas regadas',
        coordinates: { type: 'Point', coordinates: [-78.6168, -0.9358] },
        address: 'Calle Sánchez de Orellana',
        status: 'PENDING',
        verifiedByAI: false,
        pointsAwarded: 0,
        createdAt: new Date('2026-02-10T08:00:00Z'),
    },

    // === Andrés Jiménez (8 reportes) ===
    {
        userId: citizenIds[9],
        type: 'OVERFLOW',
        description: 'Contenedores del mercado completamente llenos, basura orgánica en descomposición',
        coordinates: { type: 'Point', coordinates: [-78.6148, -0.9338] },
        address: 'Mercado Cerrado, calle 2 de Mayo',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-01-16T08:00:00Z'),
        resolvedAt: new Date('2026-01-16T12:00:00Z'),
    },
    {
        userId: citizenIds[9],
        type: 'DAMAGED_CONTAINER',
        description: 'Contenedor quemado parcialmente, necesita reemplazo',
        coordinates: { type: 'Point', coordinates: [-78.6172, -0.9375] },
        address: 'Barrio El Calvario',
        status: 'RESOLVED',
        verifiedByAI: true,
        pointsAwarded: 20,
        createdAt: new Date('2026-02-01T10:00:00Z'),
        resolvedAt: new Date('2026-02-03T09:00:00Z'),
    },
    {
        userId: citizenIds[9],
        type: 'OVERFLOW',
        description: 'Punto de acopio lleno, la basura se está esparciendo con el viento',
        coordinates: { type: 'Point', coordinates: [-78.6158, -0.9328] },
        address: 'Sector La Cocha, calle Napo',
        status: 'IN_PROGRESS',
        verifiedByAI: true,
        pointsAwarded: 25,
        createdAt: new Date('2026-02-13T09:00:00Z'),
    },
];
